#!/bin/sh                                                                                       

AID="org.webosinternals.modeswitcher"
SID="org.webosinternals.modeswitcher.srv"

PID="org.webosinternals.modeswitcher.sys"

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Disable MS on update
luna-send -n 1 palm://${SID}/control '{"action":"disable"}'

# Remove the upstart file
rm -f /var/palm/event.d/${SID}

# Remove the impersonate executable
rm -f /var/usr/sbin/${PID}

# Remove the dbus service
rm -f /var/palm/system-services/${PID}.service

rm -f /var/palm/ls2/services/prv/${SID}.json
rm -f /var/palm/ls2/services/pub/${SID}.json

# Remove the ls2 roles
rm -f /var/palm/ls2/roles/prv/${PID}.json
rm -f /var/palm/ls2/roles/pub/${PID}.json

rm -f /var/palm/ls2/roles/prv/${SID}.json
rm -f /var/palm/ls2/roles/pub/${SID}.json

# Stop the service if running
/usr/bin/killall -9 ${PID} || true

# Install the impersonate executable
mkdir -p /var/usr/sbin/
install -m 755 $APPS/usr/palm/applications/${AID}/bin/impersonate /var/usr/sbin/${PID}

# Install the dbus service
mkdir -p /var/palm/system-services
cp $APPS/usr/palm/applications/${AID}/cfg/${PID}.service /var/palm/system-services/${PID}.service

mkdir -p /var/palm/ls2/services/prv /var/palm/ls2/services/pub
cp $APPS/usr/palm/applications/${AID}/cfg/${SID}.service /var/palm/ls2/services/prv/${SID}.service
cp $APPS/usr/palm/applications/${AID}/cfg/${SID}.service /var/palm/ls2/services/pub/${SID}.service

# Install the ls2 roles
mkdir -p /var/palm/ls2/roles/prv /var/palm/ls2/roles/pub
cp $APPS/usr/palm/applications/${AID}/cfg/${PID}.json /var/palm/ls2/roles/prv/${PID}.json
cp $APPS/usr/palm/applications/${AID}/cfg/${PID}.json /var/palm/ls2/roles/pub/${PID}.json

cp $APPS/usr/palm/applications/${AID}/cfg/${SID}.json /var/palm/ls2/roles/prv/${SID}.json
cp $APPS/usr/palm/applications/${AID}/cfg/${SID}.json /var/palm/ls2/roles/pub/${SID}.json

# Install the upstart file
mkdir -p /var/palm/event.d
cp $APPS/usr/palm/services/${SID}/configuration/event.d/${SID} /var/palm/event.d/${SID}

# Stop the JS service if running
/usr/bin/pkill switcher.srv.js || true

/usr/bin/ls-control scan-services || true

exit 0
