#!/bin/sh

AID="org.webosinternals.modeswitcher"
SID="org.webosinternals.modeswitcher.srv"

PID="org.webosinternals.modeswitcher.sys"

# Handle execution as pmPreRemove.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Remove the upstart file
rm -f /var/palm/event.d/${SID}

# Remove the govnah executable
rm -f /var/usr/sbin/${PID}

# Remove the dbus service
rm -f /var/palm/system-services/${PID}.service

rm -f /var/palm/ls2/services/prv/${SID}.json
rm -f /var/palm/ls2/services/pub/${SID}.json

# Remove the ls2 roles
rm -f /var/palm/ls2/roles/prv/${PID}.json
rm -f /var/palm/ls2/roles/pub/${PID}.json

rm -f /var/palm/ls2/roles/prv/${SID}.json
rm -f /var/palm/ls2/roles/pub/${SID}.json

# Stop the service if running
/usr/bin/killall -9 ${PID} || true

#
# Cleanup the JS service here due to WebOS bugs
#

/usr/bin/pkill switcher.srv.js || true

rm -f /var/cache/configurator/*webosinternals.modeswitcher*

rm -f /var/palm/ls2/roles/*/*webosinternals.modeswitcher*

rm -f /var/palm/ls2/services/*/*webosinternals.modeswitcher*

exit 0
